### ISSUE TITLE
jar compiling

### ISSUE THREAD

**Issue by jumarti** [protectwise/cassandra-util#12]
Hello. Not an issue, was hoping to get pointed in the right direction on using `deleting-compaction-strategy`

I have no knowledge on scala, I was hoping to run `sbt package`, get a jar and move on, but there's stuff to set up first and some tips will be appreciated:

```
deleting-compaction-strategy$ sbt package
[error] /home/juanc/repos/cassandra-util/deleting-compaction-strategy/src/main/java/com/protectwise/cassandra/db/columniterator/FilteringOnDiskAtomIterator.java:18:1: package com.google.common.base does not exist
 ```
and also Cassandra dependencies missing. 

Thanks.

**Comment by MightyE** [comment]
Hi @jumarti, 

Run `sbt package` from the working copy root, not from inside of `deleting-compaction-strategy/` subfolder.  

Deleting compaction strategy tests (not runtime) depend on some of the other subpaths inside the repo, so the project declaration has to exist at the upper level for it to identify those dependencies (or else get really crazy with paths).

Toward the end of the build you'll see a line like below, which will give you the jar you want:

    [info] Packaging .../deleting-compaction-strategy/target/scala-2.10/deleting-compaction-strategy-0.26-SNAPSHOT.jar ...

**Comment by jumarti** [comment]
thank you, compiling now! 
but got this error:
```
Error wrapping InputStream in GZIPInputStream: java.util.zip.ZipException: Not in GZIP format
	at sbt.ErrorHandling$.translate(ErrorHandling.scala:11)
	at sbt.WrapUsing.open(Using.scala:36)
	at sbt.Using.apply(Using.scala:24)
	at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:782)
	at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:781)
	at sbt.Using.apply(Using.scala:25)
	at sbt.IO$.gzipFileIn(IO.scala:781)
	at sbt.Sync$.readUncaught(Sync.scala:88)
	at sbt.Sync$.readInfo(Sync.scala:84)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:29)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:23)
	at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:821)
	at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:817)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at sbt.Using$$anonfun$gzipInputStream$1.apply(Using.scala:91)
	at sbt.Using$$anonfun$gzipInputStream$1.apply(Using.scala:91)
	at sbt.Using$$anon$1.openImpl(Using.scala:56)
	at sbt.WrapUsing$$anonfun$open$2.apply(Using.scala:36)
	at sbt.ErrorHandling$.translate(ErrorHandling.scala:11)
	at sbt.WrapUsing.open(Using.scala:36)
	at sbt.Using.apply(Using.scala:24)
	at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:782)
	at sbt.IO$$anonfun$gzipFileIn$1.apply(IO.scala:781)
	at sbt.Using.apply(Using.scala:25)
	at sbt.IO$.gzipFileIn(IO.scala:781)
	at sbt.Sync$.readUncaught(Sync.scala:88)
	at sbt.Sync$.readInfo(Sync.scala:84)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:29)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:23)
	at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:821)
	at sbt.Defaults$$anonfun$copyResourcesTask$1.apply(Defaults.scala:817)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
	at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (compile:copyResources) Error wrapping InputStream in GZIPInputStream: java.util.zip.ZipException: Not in GZIP format
```

**Comment by MightyE** [comment]
From a glance, you might be hitting https://github.com/sbt/sbt/issues/3050 (or similar)

Solution from that ticket is `rm -rf **/target`

**Comment by MightyE** [comment]
@jumarti when it's convenient, let me know if the above worked out for you.

**Comment by jumarti** [comment]
Hi, sorry for the delay. `rm -rf **/target` did not do it, but I just cloned the repo again and compiled with no problems!, thanks. I will be now testing the jar.
