### ISSUE TITLE
Deleting compaction strategy assertion error on restart

### ISSUE THREAD

**Issue by grddev** [protectwise/cassandra-util#2]
After applying a configuration with the deleting compaction strategy, a restart of Cassandra results in a couple of stack traces like these:

```
ERROR [CompactionExecutor:1] 2016-12-16 17:22:51,832 DeletingCompactionStrategyOptions.java:124 - Unable to instantiate convictor class com.protectwise.cassandra.retrospect.deletion.RuleBasedLateTTLConvictor: null
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_71]
	at com.protectwise.cassandra.db.compaction.DeletingCompactionStrategyOptions.buildConvictor(DeletingCompactionStrategyOptions.java:120) ~[deleting-compaction-strategy-0.24-SNAPSHOT.jar:0.24-SNAPSHOT]
	at com.protectwise.cassandra.db.compaction.DeletingCompactionStrategy.getScanners(DeletingCompactionStrategy.java:103) [deleting-compaction-strategy-0.24-SNAPSHOT.jar:0.24-SNAPSHOT]
	at org.apache.cassandra.db.compaction.WrappingCompactionStrategy.getScanners(WrappingCompactionStrategy.java:357) [apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.db.compaction.AbstractCompactionStrategy.getScanners(AbstractCompactionStrategy.java:349) [apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.db.compaction.CompactionTask.runMayThrow(CompactionTask.java:164) [apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.utils.WrappedRunnable.run(WrappedRunnable.java:28) [apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.db.compaction.CompactionTask.executeInternal(CompactionTask.java:73) [apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.db.compaction.AbstractCompactionTask.execute(AbstractCompactionTask.java:59) [apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.db.compaction.CompactionManager$BackgroundCompactionTask.run(CompactionManager.java:244) [apache-cassandra-2.1.8.jar:2.1.8]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_71]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.AssertionError: null
	at org.apache.cassandra.locator.TokenMetadata.firstTokenIndex(TokenMetadata.java:755) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.locator.TokenMetadata.firstToken(TokenMetadata.java:769) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.locator.AbstractReplicationStrategy.getNaturalEndpoints(AbstractReplicationStrategy.java:107) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.service.StorageService.getLiveNaturalEndpoints(StorageService.java:3146) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.service.StorageProxy.getLiveSortedEndpoints(StorageProxy.java:1526) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.service.StorageProxy.getLiveSortedEndpoints(StorageProxy.java:1521) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.service.AbstractReadExecutor.getReadExecutor(AbstractReadExecutor.java:155) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.service.StorageProxy.fetchRows(StorageProxy.java:1328) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.service.StorageProxy.readRegular(StorageProxy.java:1270) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.service.StorageProxy.read(StorageProxy.java:1193) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:271) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:224) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.cql3.statements.SelectStatement.execute(SelectStatement.java:67) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.cql3.QueryProcessor.processStatement(QueryProcessor.java:238) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:260) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at org.apache.cassandra.cql3.QueryProcessor.process(QueryProcessor.java:272) ~[apache-cassandra-2.1.8.jar:2.1.8]
	at com.protectwise.cassandra.retrospect.deletion.RuleBasedLateTTLConvictor.parseRules(RuleBasedLateTTLConvictor.java:206) ~[deleting-compaction-strategy-0.24-SNAPSHOT.jar:0.24-SNAPSHOT]
	at com.protectwise.cassandra.retrospect.deletion.RuleBasedLateTTLConvictor.<init>(RuleBasedLateTTLConvictor.java:189) ~[deleting-compaction-strategy-0.24-SNAPSHOT.jar:0.24-SNAPSHOT]
	... 18 common frames omitted
```

This seems to be related to compactions being triggered before the local Cassandra process has fully joined the ring, and thus executing the CQL query to get the deletion rules doesn't really work. It seems like the errors were effectively ignored and eventually compactions started executing correctly.

**Comment by MightyE** [comment]
If the statement fails for any reason, it'll enter a "spooked" state and just revert to standard compactions.  You're right, this is probably compaction happening before fully joining the ring, so the rules table can't be queried.  

I'm not sure what the best way to handle this, I dislike something producing errors on startup, maybe we should have it test whether it's fully joined the ring, and during startup, if the query fails, swallow the error (and remain spooked) - only log the error after fully joined.

**Comment by MightyE** [comment]
Do you want to take a look at [bug/issue-2](https://github.com/protectwise/cassandra-util/pull/3) and see if this branch does what I think it should?  I'm not sure if there's a better way to tell if the node is joined to the ring or not, I couldn't find anything in the startup process that sets a flag indicating initialization and gossip are fully done.

I haven't been able to repro the compactions starting before fully joined, so it's hard for me to test.

**Comment by grddev** [comment]
I finally got around to trying out #3 in our staging environment today, and can sadly report that it behaves identically. Now that I look at it again, that is not so surprising, as it throws an `AssertionError`, whereas the PR only captures a `RequestExecutionException`. I'm not sure whether catching the error would be such a good idea, but I'm also not really sure how to avoid it.

I guess an alternative would be to do something along the lines of

```java
public boolean hasStartedCQL() {
  try {
    new Socket(DatabaseDescriptor.getRpcAddress(), DatabaseDescriptor.getNativeTransportPort()).close();
    return true;
  } catch (IOException e) {
    return false;
  }
}
```

before issuing the query for the first time.

**Comment by MightyE** [comment]
I'm not real keen on opening a socket connection for each compaction just to check whether the node is fully joined.  It seems like there has to be a better approach (though I guess we could do that just until it finally connected once).  

You're right, I don't think I'm catching the exception, so the code I wrote isn't actually kicking in. I added a check just prior to executing the query instead of trying to catch the execution exception (as you pointed out I wasn't catching the `AssertionError` so my code wasn't actually doing anything).

Can you give the updated branch a try and see if this prevents the error?  If not then I think it's a matter of figuring out what the right way to test for fully-joined status is.

**Comment by grddev** [comment]
> I'm not real keen on opening a socket connection for each compaction just to check whether the node is fully joined.

The intention with "for the first time" was that this information would be cached by the compaction strategy so that it was only used until it has returned true for the first time.

To clarify, the reason I suggested the Socket-based solution is because as far as I understand it, the current check only verifies that gossip has been enabled, and not that it has actually reached a stable (or even usable) state yet. Expressed differently, the check currently in #3 seems prone to race conditions.

> Can you give the updated branch a try and see if this prevents the error?

In our test setup, it seems compactions are triggered immediately before gossip is started, and when I tried took long enough to complete that the follow-up compaction only happened after gossip had settled. Thus, it does indeed workaround the issue. But, as I argued above, it doesn't seem to do so deterministically.

Also, I'm not really sure reverting to a normal compaction is ideal, as this will then potentially introduce further delay until data has been deleted from all SSTables. It also makes it even more complicated to track when all data for a particular rule has been deleted.

Would it not be better to pause compactions until the ring is available, possibly by returning false from `DeletingCompactionStrategy#isEnabled()` or simply blocking in the Compaction task until possible.

**Comment by MightyE** [comment]
> The intention with "for the first time" was that this information would be cached by the compaction strategy so that it was only used until it has returned true for the first time

Well we need to think about what to do later on in the life of the cluster too, such as if someone did `nodetool disablegossip` and related calls.

> Also, I'm not really sure reverting to a normal compaction is ideal, as this will then potentially introduce further delay until data has been deleted from all SSTables. 

It seems to me dangerous to completely disable compaction when rules can't be read.  There may be other causes of failing to read rules that aren't as transient as the node not having fully joined yet.   For example the rules table has been corrupted in some way (schema got changed, invalid data written to table, etc.), or offline nodes might fail quorum reads of the rules (we read at quorum so that if the rules are written at quorum we have immediate consistency).  In such a case you could dramatically hurt cluster health by refusing to do any compaction at all.

Instead we could degrade to disabled compaction only during the startup stage.  However, degrading to disabling compaction only during startup but degrading to standard compaction during other errors is the kind of inconsistency which might be in violation of the principle of least surprise.

> It also makes it even more complicated to track when all data for a particular rule has been deleted.

That's a valid concern, because if you have a situation where you *must* clean up data (data spillage for example), not having confidence that all candidate sstables have been through an operational version of the deleter would make this challenging for sure.  

Still, my initial feeling is that cluster health trumps data governance, as clusters which are behind on compaction are at a very real risk of dropping mutations due to i/o starvation, and it's difficult to correct that problem because the solutions all involve increasing i/o pressure.  

Perhaps an option on the rule based convictors for how to degrade when rules can't be read is in order.  I'd definitely be amenable to a pull request for that once we figure out how to definitely know whether it's safe to query.

I'm going to take the question of "How do I know I'm fully joined" to the dev list, because I'm basically just guessing at this point.  I made another stab at detecting this in 31ece5e, but I'll find out what the dev list thinks of this approach.

**Comment by MightyE** [comment]
I got a good reply from Brandon on the dev@ list with a better way to know if it's safe to query CQL.   See fa0ee9c

Brandon points out that bootstrapping nodes haven't joined the ring yet, and the native transport isn't running, so they are not able to issue queries in this space either.  Disabling compaction when not joined to the ring means that a bootstrapping node is unable to compact (and there's a lot of compaction that needs to happen during bootstrap), so degrading to a disabled state when the rules query can't be executed would be catastrophic for a bootstrapping node.

**Comment by grddev** [comment]
> Brandon points out that bootstrapping nodes haven't joined the ring yet, and the native transport isn't running, so they are not able to issue queries in this space either. Disabling compaction when not joined to the ring means that a bootstrapping node is unable to compact (and there's a lot of compaction that needs to happen during bootstrap), so degrading to a disabled state when the rules query can't be executed would be catastrophic for a bootstrapping node.

My reasoning for using the Socket to identify if Cassandra was up and running was due to the fact that the CassandraDaemon launched the native server after waiting for Gossip to settle, given that the newly proposed checks essentially check the same thing (but without actually resorting to sockets), it seems like a reasonable solution to me.

Also, I guess falling back on a regular compaction is probably the best available option, given the circumstances. For my purposes, it would be nice there was a way to determine whether (and when) an SSTable had passed through the deleting compaction strategy, but that discussion isn't really on topic for this issue.
